import { useMemo, useState } from "react";
import { TriangleAlert, X } from "lucide-react";

import type { ExtensionReport } from "@amibeingpwned/types";
import {
  Table,
  TableBody,
  TableHead,
  TableHeader,
  TableRow,
} from "@amibeingpwned/ui/table";

import type { ReportMap } from "~/hooks/use-extension-database";
import { riskOrder } from "~/lib/risk";
import { DatabaseRow } from "~/components/database-row";

export function DatabaseSection({ reports }: { reports: ReportMap }) {
  const [search, setSearch] = useState("");
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [showDisclaimer, setShowDisclaimer] = useState(true);

  const dbEntries = useMemo(() => {
    const riskWeight: Record<string, number> = {
      critical: 5,
      high: 4,
      "medium-high": 3,
      medium: 2,
      "medium-low": 1.5,
      low: 1,
      clean: 0,
      unavailable: 0,
    };
    const score = (ext: ExtensionReport) =>
      (riskWeight[ext.risk] ?? 0) * Math.log10(Math.max(ext.userCount, 1));
    return [...reports.entries()]
      .sort(([, a], [, b]) => score(b) - score(a));
  }, [reports, reports.size]);

  const filtered = useMemo(() => {
    if (!search.trim()) return dbEntries;
    const q = search.toLowerCase();
    return dbEntries.filter(
      ([id, ext]) =>
        ext.name.toLowerCase().includes(q) ||
        id.toLowerCase().includes(q) ||
        ext.summary.toLowerCase().includes(q),
    );
  }, [dbEntries, search]);

  return (
    <section id="database" className="mx-auto max-w-6xl px-6 py-16">
      <div className="mb-6 flex items-end justify-between gap-4">
        <div>
          <h2 className="text-foreground text-xl font-semibold">
            Extension Database
          </h2>
          <p className="text-muted-foreground text-sm">
            {filtered.length} extension{filtered.length !== 1 ? "s" : ""}{" "}
            flagged
          </p>
        </div>
        <input
          type="text"
          placeholder="Search extensions..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="border-border bg-background text-foreground placeholder:text-muted-foreground w-64 rounded-md border px-3 py-1.5 text-sm outline-none focus:ring-1 focus:ring-zinc-500"
        />
      </div>

      {showDisclaimer && (
        <div className="border-border bg-card mb-4 flex items-start gap-3 rounded-lg border p-4">
          <TriangleAlert className="text-yellow-500 mt-0.5 h-4 w-4 shrink-0" />
          <p className="text-muted-foreground text-sm">
            Reports are primarily generated by AI and do contain some inaccuracies.
            These reports need to be manually validated beforehand.
            Always verify findings independently before taking action. This tool
            is not a substitute for a professional security audit.
          </p>
          <button
            onClick={() => setShowDisclaimer(false)}
            className="text-muted-foreground hover:text-foreground shrink-0 p-0.5"
          >
            <X className="h-4 w-4" />
          </button>
        </div>
      )}

      <div className="border-border overflow-hidden rounded-lg border">
        <Table className="table-fixed">
          <TableHeader>
            <TableRow>
              <TableHead>Extension</TableHead>
              <TableHead className="w-20">Users</TableHead>
              <TableHead className="w-24">Risk</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {filtered.map(([id, ext]) => (
              <DatabaseRow
                key={id}
                id={id}
                ext={ext}
                isExpanded={expandedId === id}
                onToggle={() => setExpandedId(expandedId === id ? null : id)}
              />
            ))}
          </TableBody>
        </Table>
      </div>
    </section>
  );
}
